[workspace]
channels = ["conda-forge"]
name = "summer3template"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
summer3 = { git = "https://github.com/monash-emu/summer3wip.git" }
example_project = { path = "src/example_project", editable = true }
arviz = "==0.23.4"
plotly = ">=6.6.0, <7"
ipywidgets = ">=8.1.8, <9"
nbformat = ">=5.10.4, <6"
jax = ">=0.9"
jaxlib = ">=0.9"
diffrax = ">=0.7.2, <0.8"
numpyro = ">=0.20.0, <0.21"
jupyterlab = ">=4.5.6, <5"
jupyterlab-git = ">=0.52.0, <0.53"

